In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
cd "d:/Semester 6/FIT3162/Fakeddit"

d:\Semester 6\FIT3162\Fakeddit


In [3]:
df = pd.read_csv('dataset.csv', index_col = 0)

In [6]:
# from nltk import tokenize
# from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
# analyser = SentimentIntensityAnalyzer()
# def post_sentiment(post):
#     sentiment_score = analyser.polarity_scores(post)["compound"]
#     return sentiment_score
# df['post_sentiment'] = df.apply(lambda x: post_sentiment(x['title']), axis=1)

In [7]:
df.head(2)

clean_title          created_utc  \
0  can i still cash in my brain needs to rest  2017-06-17 12:58:22   
1  how did the wheat say to its son photoshop  2019-07-27 18:58:22   

                    domain      id  num_comments  score           subreddit  \
0  self.SubredditSimulator  6hrnqx            20     17  subredditsimulator   
1  self.SubredditSimulator  cig6ey            20      3  subredditsimulator   

                                         title  2_way_label  \
0   Can I still cash in my brain needs to rest            0   
1  How did the wheat say to its son Photoshop?            0   

   comment_sentiment  domain_rank  upvote_ratio  post_sentiment  
0          -0.034000      1000001           0.9             0.0  
1           0.196715      1000001           1.0             0.0

##### Splitting the Dataset into Test and Traning Set

In [16]:
from sklearn.model_selection import train_test_split
# separate array into features and target
X = np.array(df[['comment_sentiment','post_sentiment', 'domain_rank', 'upvote_ratio']])
Y = np.array(df['2_way_label'])
# 75:25 ratio of training and test set.
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=123)

#### Perform Rescaling of Data using MinMaxScaler

In [28]:
# Rescale data (between 0 and 1)
import scipy
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# summarize transformed data
np.set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[ 0.438  0.5    1.     0.792]
 [ 0.616  0.5    1.     1.   ]
 [ 0.456  0.486  1.     0.854]
 [ 0.443  0.137  1.     0.583]
 [ 0.475  0.345  0.001  0.521]]


#### Logistic Regression Model Classifier

In [29]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))

Accuracy of Logistic regression classifier on training set: 0.77
Accuracy of Logistic regression classifier on test set: 0.76


#### Decision Tree

In [30]:
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.81


##### KNN

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.85
Accuracy of K-NN classifier on test set: 0.78


#### Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

Accuracy of GNB classifier on training set: 0.77
Accuracy of GNB classifier on test set: 0.77


##### Support Vector Machine

In [39]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

Accuracy of SVM classifier on training set: 0.76
Accuracy of SVM classifier on test set: 0.76


#### Random Forest

In [40]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=123)
RF.fit(X_train, y_train)
print('Accuracy of RF classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of RF classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

Accuracy of RF classifier on training set: 0.76
Accuracy of RF classifier on test set: 0.76


#### Confusion Matrix for Decision Tree

In [38]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = clf.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[1038  224]
 [ 258  980]]
             precision    recall  f1-score   support

          0       0.80      0.82      0.81      1262
          1       0.81      0.79      0.80      1238

avg / total       0.81      0.81      0.81      2500

